# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/achievement_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AchievementDialog(object):
    def setupUi(self, AchievementDialog):
        AchievementDialog.setObjectName("AchievementDialog")
        AchievementDialog.resize(460, 560)
        self.achDialogRootLayout = QtWidgets.QVBoxLayout(AchievementDialog)
        self.achDialogRootLayout.setContentsMargins(22, 22, 22, 18)
        self.achDialogRootLayout.setSpacing(12)
        self.achDialogRootLayout.setObjectName("achDialogRootLayout")
        self.achGameTitleLabel = QtWidgets.QLabel(AchievementDialog)
        self.achGameTitleLabel.setProperty("objectName", "achGameTitleLabel")
        self.achGameTitleLabel.setObjectName("achGameTitleLabel")
        self.achDialogRootLayout.addWidget(self.achGameTitleLabel)
        self.achProgressBar = QtWidgets.QProgressBar(AchievementDialog)
        self.achProgressBar.setMinimumSize(QtCore.QSize(0, 22))
        self.achProgressBar.setProperty("value", 0)
        self.achProgressBar.setProperty("objectName", "achProgressBar")
        self.achProgressBar.setObjectName("achProgressBar")
        self.achDialogRootLayout.addWidget(self.achProgressBar)
        self.achListWidget = QtWidgets.QListWidget(AchievementDialog)
        self.achListWidget.setProperty("objectName", "achListWidget")
        self.achListWidget.setObjectName("achListWidget")
        self.achDialogRootLayout.addWidget(self.achListWidget)
        self.achAddRowLayout = QtWidgets.QHBoxLayout()
        self.achAddRowLayout.setObjectName("achAddRowLayout")
        self.newAchNameEdit = QtWidgets.QLineEdit(AchievementDialog)
        self.newAchNameEdit.setProperty("objectName", "newAchNameEdit")
        self.newAchNameEdit.setObjectName("newAchNameEdit")
        self.achAddRowLayout.addWidget(self.newAchNameEdit)
        self.addAchBtn = QtWidgets.QPushButton(AchievementDialog)
        self.addAchBtn.setProperty("objectName", "addAchBtn")
        self.addAchBtn.setObjectName("addAchBtn")
        self.achAddRowLayout.addWidget(self.addAchBtn)
        self.achDialogRootLayout.addLayout(self.achAddRowLayout)
        self.newAchDescEdit = QtWidgets.QLineEdit(AchievementDialog)
        self.newAchDescEdit.setProperty("objectName", "newAchDescEdit")
        self.newAchDescEdit.setObjectName("newAchDescEdit")
        self.achDialogRootLayout.addWidget(self.newAchDescEdit)
        self.achButtonsLayout = QtWidgets.QHBoxLayout()
        self.achButtonsLayout.setObjectName("achButtonsLayout")
        self.removeAchBtn = QtWidgets.QPushButton(AchievementDialog)
        self.removeAchBtn.setProperty("objectName", "removeAchBtn")
        self.removeAchBtn.setObjectName("removeAchBtn")
        self.achButtonsLayout.addWidget(self.removeAchBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.achButtonsLayout.addItem(spacerItem)
        self.closeAchBtn = QtWidgets.QPushButton(AchievementDialog)
        self.closeAchBtn.setProperty("objectName", "closeAchBtn")
        self.closeAchBtn.setObjectName("closeAchBtn")
        self.achButtonsLayout.addWidget(self.closeAchBtn)
        self.achDialogRootLayout.addLayout(self.achButtonsLayout)

        self.retranslateUi(AchievementDialog)
        QtCore.QMetaObject.connectSlotsByName(AchievementDialog)

    def retranslateUi(self, AchievementDialog):
        _translate = QtCore.QCoreApplication.translate
        AchievementDialog.setWindowTitle(_translate("AchievementDialog", "Achievements"))
        self.achGameTitleLabel.setText(_translate("AchievementDialog", "Achievements for Game"))
        self.newAchNameEdit.setPlaceholderText(_translate("AchievementDialog", "New achievement name..."))
        self.addAchBtn.setText(_translate("AchievementDialog", "＋ Add"))
        self.newAchDescEdit.setPlaceholderText(_translate("AchievementDialog", "Description (optional)..."))
        self.removeAchBtn.setText(_translate("AchievementDialog", "Remove Selected"))
        self.closeAchBtn.setText(_translate("AchievementDialog", "Close"))
